import streamlit as pd_stream
import duckdb
import pandas as pd
import time

# ─── CONFIRM PAGE CONFIGURATION ───
pd_stream.set_page_config(
    page_title="Real-Time Crypto Lakehouse Mart",
    page_icon="📊",
    layout="wide"
)

# Connect to the local DuckDB file generated by your dbt run
DB_PATH = "analytics_warehouse/analytics_lakehouse.duckdb"

def fetch_warehouse_data():
    """Opens a connection, injects local MinIO settings, and fetches metrics."""
    conn = duckdb.connect(DB_PATH)
    
    # Force credentials for the active session to view raw/staging layers if needed
    conn.execute("SET s3_endpoint='localhost:9000';")
    conn.execute("SET s3_access_key_id='admin_key';")
    conn.execute("SET s3_secret_access_key='secret_session_password';")
    conn.execute("SET s3_use_ssl=false;")
    conn.execute("SET s3_url_style='path';")
    
    # Query our Gold Mart table created by dbt
    df_trends = conn.execute("SELECT * FROM main.fct_hourly_market_trends ORDER BY trend_hour ASC;").fetchdf()
    conn.close()
    return df_trends

# ─── FRONTEND HEADER ───
pd_stream.title("🛰️ Real-Time Cloud Data Lakehouse Monitor")
pd_stream.markdown("This dashboard queries your local **DuckDB Warehouse Layer**, which continuously reads structured columnar Parquet drops from your **MinIO S3 Data Lake**.")

# Add a manual refresh anchor point
if pd_stream.button("🔄 Force Refresh Metrics"):
    pd_stream.rerun()

try:
    df = fetch_warehouse_data()

    if not df.empty:
        # Get the latest row for our top KPI scorecards
        latest_row = df.iloc[-1]
        
        # ─── METRIC SCORECARDS ───
        col1, col2, col3, col4 = pd_stream.columns(4)
        col1.metric(label="BTC Average Price", value=f"${latest_row['avg_bitcoin_price']:,}")
        col2.metric(label="ETH Average Price", value=f"${latest_row['avg_ethereum_price']:,}")
        col3.metric(label="SOL Average Price", value=f"${latest_row['avg_solana_price']:,}")
        col4.metric(label="Heartbeat Ticks (Hour)", value=int(latest_row['total_heartbeat_ticks_received']))

        pd_stream.markdown("---")

        # ─── TIME SERIES VISUALIZATIONS ───
        pd_stream.subheader("📈 Asset Price Trends Over Time (Hourly Aggregates)")
        
        # Create separate tabs for each cryptocurrency trend line
        tab1, tab2, tab3 = pd_stream.tabs(["Bitcoin (BTC)", "Ethereum (ETH)", "Solana (SOL)"])
        
        with tab1:
            pd_stream.line_chart(data=df, x="trend_hour", y="avg_bitcoin_price", use_container_width=True)
        with tab2:
            pd_stream.line_chart(data=df, x="trend_hour", y="avg_ethereum_price", use_container_width=True)
        with tab3:
            pd_stream.line_chart(data=df, x="trend_hour", y="avg_solana_price", use_container_width=True)

        # ─── RAW DATA LOG VIEW ───
        pd_stream.subheader("📋 Underlying Warehouse Data Mart (`fct_hourly_market_trends`)")
        pd_stream.dataframe(df.sort_values(by="trend_hour", ascending=False), use_container_width=True)
        
    else:
        pd_stream.warning("Warehouse tables loaded successfully, but they appear to be empty. Ensure you ran `dbt run` inside your analytics directory!")

except Exception as e:
    pd_stream.error(f"Could not connect to the database engine: {e}")